package:
  name: fomms_integrate
  version: "0.0.0"

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - fomms_integrate

about:
  home: add_url_here
  license: LGPLv3 License
